### PR TITLE
Emojis for all

### LINKED ISSUE #615: Emoji overview
There should be an easy way to select one of the available emojis when writing a document (e.g. emoji list in a modal).

### PR DESCRIPTION
**Pull request by Bartzi**
fixes #615

### CODE REVIEW

**Comment by Bartzi** [comment]
alright I removed all CDNs please check again =)

**Comment by janno42** [comment]
can we do something against the different renderings in the three views?:

## edit textbox


## preview


## saved page

**Comment by janno42** [comment]
unfortunately the emoji picker currently does not really work in full screen mode (because it's mostly located outside the window then) and it also limits the textbox size to a smaller part of the screen. could you please have a look into this?

**Comment by Bartzi** [comment]
I don't know the exact cause of  the different renderings, but I suspect it is because on Windows emojis might be loaded differently. On Linux I can not see any differences in those three different examples.

I fixed the positioning of the emojiarea in fullscreen mode. Unfortunately, we can not use the autocomplete, that is invoked via typing `:` in fullscreen because we can't change the `z-index` of this autocomplete without rewriting the library, which is not advisable.
But it is still possible to add emojis^^

**Comment by janno42** [comment]
unfortunately still broken. when typing `:` in full screen, the emoji picker moves to the right when opening it again.

**Comment by Bartzi** [comment]
please have a look again ;)

**Comment by janno42** [comment]
the height of the textbox in fullscreen is still too small and the modals for inserting internal links and images is broken.

**Comment by janno42** [comment]
it looks like the modals were a caching error on my site, so please disregard

**Comment by janno42** [comment]
can you please add:
```
.emojionearea md-input {
    height: 450px;
}
.emojionearea-editor {
    height: 100%;
    max-height: none;
}
```

**Comment by Bartzi** [comment]
Please check again, I found another bug in fullscreen mode...
when pressing repeatedly on one emoji, the picker went to the right and out of the window. This should now be fixed.

**Pull request merged**
