### PR TITLE
make it possible to use urls with trailing slash or without

### LINKED ISSUE #506: Trailing slashes in URL
URLs should be resolvable with or without trailing slashes.

### PR DESCRIPTION
**Pull request by Bartzi**
fix #506

### CODE REVIEW

**Comment by janno42** [comment]
I don't really like URLs with trailing slashes, so I would prefer using URLs without slash, it should only be possible to access the page even with a trailing slash.

**Comment by Bartzi** [comment]
Yes we can do this...
I could implement it using [this](https://djangosnippets.org/snippets/2655/) middleware...

**Comment by janno42** [comment]
and what about `.../?` in the regexes?

**Comment by Bartzi** [comment]
very good idea! That actually seems to work quite well! Please have a look again

**Comment by janno42** [comment]
it does not work with information pages (`.../infopage/` does not resolve if the url title is `infopage`)

**Comment by Bartzi** [comment]
yeah right... well in this case I do not see any other possibilty, but implementing the middleware because we can not really add this to URLs we chose by ourselves...

**Comment by janno42** [comment]
Well, we could adapt the document retrieval and remove trailing slashes in the view.

**Comment by Bartzi** [comment]
obsoleted by #519

**Pull request closed without merging**
